const crypto = require('crypto');
const db = require('../config/db');
const { createRoom } = require('../websocket/roomManager');

/**
 * POST /api/internal/sessions
 *
 * Called by Matching Service when a match is found.
 * sessionId is generated by Matching Service and passed in the body.
 *
 * Body: { sessionId, userOneId, userTwoId, question }
 * Returns: { success: true, data: { sessionId, roomId } }
 *
 * TODO: re-enable serviceAuthMiddleware once Matching Service sends X-Service-Secret header
 */
const createSession = async (req, res) => {
  const { sessionId, userOneId, userTwoId, question } = req.body;

  if (!sessionId || !userOneId || !userTwoId || !question?.questionId) {
    return res.status(400).json({
      success: false,
      message: 'sessionId, userOneId, userTwoId, and question.questionId are required',
    });
  }

  const roomId = crypto.randomUUID();

  try {
    await db.query(
      `INSERT INTO "session" ("sessionId", "roomId", "questionId", "userOneId", "userTwoId")
       VALUES ($1, $2, $3, $4, $5)`,
      [sessionId, roomId, question.questionId, userOneId, userTwoId]
    );

    createRoom(roomId, {
      sessionId,
      questionId: question.questionId,
      question,
      userOneId,
      userTwoId,
    });

    return res.status(201).json({
      success: true,
      data: { sessionId, roomId },
    });
  } catch (err) {
    if (err.code === '23505') {
      // Unique constraint — duplicate sessionId or roomId
      return res.status(409).json({
        success: false,
        message: 'Session already exists',
      });
    }
    console.error('POST /api/internal/sessions error:', err);
    return res.status(500).json({ success: false, message: 'Internal server error' });
  }
};

/**
 * GET /api/internal/sessions/:sessionId
 *
 * Called by Matching Service to check session status.
 */
const getSession = async (req, res) => {
  const { sessionId } = req.params;

  try {
    const result = await db.query(
      `SELECT * FROM "session" WHERE "sessionId" = $1`,
      [sessionId]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ success: false, message: 'Session not found' });
    }

    return res.status(200).json({ success: true, data: result.rows[0] });
  } catch (err) {
    console.error('GET /api/internal/sessions/:sessionId error:', err);
    return res.status(500).json({ success: false, message: 'Internal server error' });
  }
};

module.exports = { createSession, getSession };
